# Q-Table Learning

In [1]:
import gym
import numpy as np

### Load the environment

In [2]:
env = gym.make('FrozenLake-v0')

[2017-10-08 22:35:49,470] Making new env: FrozenLake-v0


### Implement Q-Table learning algorithm

In [3]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [5]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.4585


In [6]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[  9.46406714e-02   6.08959552e-03   7.20730362e-03   7.83064331e-03]
 [  3.06002737e-03   2.06481524e-03   1.45893407e-03   1.67163771e-01]
 [  1.57650865e-01   1.35942385e-03   1.11281660e-03   3.74712145e-03]
 [  3.43474865e-04   1.19303188e-04   9.24128656e-04   3.78849979e-03]
 [  7.65095095e-02   7.01667612e-03   1.66438575e-03   1.46095506e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  5.18253395e-03   1.33210463e-08   7.56224732e-04   1.32879857e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.00111309e-04   1.45836006e-03   1.30942921e-03   7.41773649e-02]
 [  8.08306111e-04   8.40696276e-02   0.00000000e+00   0.00000000e+00]
 [  1.09495981e-01   2.53613295e-04   4.67850098e-04   7.16851867e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   5.49809485e-04   9.02796047e-02   0